name = "design-portfolio-2025-b"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
workers_dev = false

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

routes = [
  "https://design-portfolio-2025-b.ogum536.workers.dev/",
]
